//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canteen_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_View
    {
        public string Alias { get; set; }
        public string Name { get; set; }
        public string Meal_Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Break_First { get; set; }
        public string Lunch { get; set; }
        public string Dinner { get; set; }
        public string Extra { get; set; }
        public Nullable<double> Extra_Price { get; set; }
        public Nullable<double> Total_Price { get; set; }
    }
}
