//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canteen_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Meal_Operation
    {
        public string Alias { get; set; }
        public string Name { get; set; }
        public string Meal_Status { get; set; }
        public string Req_Meal_Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Limit { get; set; }
    }
}
