//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canteen_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Due
    {
        public string Alias { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> Paid_Amt { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Payment_Mode { get; set; }
    }
}
