//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canteen_Management_System.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Canteen_ManagementEntities : DbContext
    {
        public Canteen_ManagementEntities()
            : base("name=Canteen_ManagementEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_Mst> Admin_Mst { get; set; }
        public virtual DbSet<Amount> Amounts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Payment_Details> Payment_Details { get; set; }
        public virtual DbSet<Meal> Meals { get; set; }
        public virtual DbSet<Extra_Item> Extra_Item { get; set; }
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<Attendance_Mng_View> Attendance_Mng_View { get; set; }
        public virtual DbSet<Attendance_View> Attendance_View { get; set; }
        public virtual DbSet<Meal_OnOff> Meal_OnOff { get; set; }
        public virtual DbSet<Customer_Meal_Operation> Customer_Meal_Operation { get; set; }
        public virtual DbSet<OnlinePayment> OnlinePayments { get; set; }
        public virtual DbSet<Monthly_Due> Monthly_Due { get; set; }
        public virtual DbSet<Customer_Due> Customer_Due { get; set; }
        public virtual DbSet<Public_Query> Public_Query { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
    }
}
