//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canteen_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly_Due
    {
        public int Md_Id { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public int Month { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
