//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canteen_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class OnlinePayment
    {
        public int Op_Id { get; set; }
        public string Alias { get; set; }
        public string Tran_Id { get; set; }
        public double Amount { get; set; }
        public string Image { get; set; }
        public HttpPostedFileBase File { get; set; }
        public string Pay_Status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
