//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Canteen_Management_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Public_Query
    {
        public int Q_id { get; set; }
        public string Name { get; set; }
        public Nullable<long> Mobile { get; set; }
        public string G_Mail { get; set; }
        public string Query { get; set; }
    }
}
